### ISSUE TITLE
enhance.py can not run

### ISSUE THREAD

**Issue by cshopping** [budui/Control-Units-in-StyleGAN2#1]
First of all thank you for your outstanding work
I get the following error when I run enhance.py. Can you tell me how to run this script?
(i run interfacegan.py to get the initial modification_path, only add move on layer 16.)

Control-Units-in-StyleGAN2/tools/manipulation/../../models/StyleGAN2.py", line 95, in forward
    w = weight * style.view(batch_size, -1, in_channel, 1, 1)  # N x O x I x Kw x kh
RuntimeError: The size of tensor a (512) must match the size of tensor b (511) at non-singleton dimension 1

**Comment by budui** [comment]
I'm sorry I haven't updated the documentation due to some personal matters. 
I'm not sure exactly what this error is about yet, I'll check and respond over the weekend.

**Comment by cshopping** [comment]
thank you very much.
I think it’s because I misused somewhere. to save your time, can you briefly explain how to use enhance.py?
the error detail is:
for example: if the batch size is 2, and the style.shape will be (2,512); after Manipulator.apply(), the style become, (2,512,512); 
in the ModulatedConv2d  this line:
       if not fused_modconv:
            x = x * style.to(x.dtype).reshape(batch_size, -1, 1, 1)
after style.to(x.dtype).reshape(batch_size, -1, 1, 1), the shape will become [2, 262144, 1, 1], it cannot be multiplied by x of shape [2, 512, 16, 16]

exception detail is:
 File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "enhance.py", line 103, in prev
    _, feature = G.styles_to_image_and_features(
  File "/home/test/work/ml/Control-Units-in-StyleGAN2/tools/manipulation/../../models/StyleGAN2_wrapper.py", line 133, in styles_to_image_and_features
    out = conv1(out, styles[i], noise=noise1)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/test/work/ml/Control-Units-in-StyleGAN2/tools/manipulation/../../models/StyleGAN2.py", line 213, in forward
    out = self.conv(x, w, noise=self.noise(x, noise))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/test/work/ml/Control-Units-in-StyleGAN2/tools/manipulation/../../models/StyleGAN2.py", line 111, in forward
    x = x * style.to(x.dtype).reshape(batch_size, -1, 1, 1)
RuntimeError: The size of tensor a (512) must match the size of tensor b (262144) at non-singleton dimension 1

**Comment by budui** [comment]
```bash
# only keep high correction channels & show the editing results.
python3 manipulation.py test --max_factor 12 --batch_size 8 --seed 8 \
 --build_mdfc_way alter --mdfc_path ./tmp/w_Gray_Hair.mdfc --layers 12 --rules "ric[10]>0.2"
 
# only keep high correction channels. & save the mdfc file
PYTHONPATH=. python3 editing/modification.py alter --mdfc_path ./tmp/w_Gray_Hair.mdfc --layers 12 --rules "ric[10]>0.2"

# enhance feature maps
PYTHONPATH=. python3 ./tools/manipulation/enhance.py prev ./tmp/alter_w_Gray_Hair.mdfc 10 \
 --checkpoint /path/to/stylegan2.checkpoint \
 --batch_size 16
```

**Comment by cshopping** [comment]
thx.
i do like your suggest. the error is the same

**Comment by budui** [comment]
Hi, please add `G.eval()` as the new [commit](https://github.com/budui/Control-Units-in-StyleGAN2/commit/3a1aa9f05c376fe321a85c6b9c8f61463a77f284).

Because these line use `self.training`  to determine the flag `fused_modconv`.

https://github.com/budui/Control-Units-in-StyleGAN2/blob/3a1aa9f05c376fe321a85c6b9c8f61463a77f284/models/StyleGAN2.py#L70-L71

**Comment by cshopping** [comment]
thank you very much.
it work now
