### ISSUE TITLE
How to calculate correction.pt?

### ISSUE THREAD

**Issue by ty625911724** [budui/Control-Units-in-StyleGAN2#2]
Hi, Thanks a lot for your exciting works!

In this code, I find it directly loads the correction.pt to find the channels for specific semantic masks.
However, I do not find the code to calculate correction.pt.

Is the corresponding part included in this repository? Or could you kindly release it? 
Thanks!

**Comment by budui** [comment]
Yes, please refer to `tools/manipulation/analysis_channel.py` (You should download `pretrained/BiSetNet.pth` at first.)
```bash
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=.  python3 tools/manipulation/analysis_channel.py $checkpoint_path $correction_path
```
The support arguments of this cli tool is the same as the function signature:
https://github.com/budui/Control-Units-in-StyleGAN2/blob/c80779561763a5f44be04e11ba35276307426b2e/tools/manipulation/analysis_channel.py#L12
