### ISSUE TITLE
google云盘上少了两个pretrain model

### ISSUE THREAD

**Issue by seasm** [budui/Control-Units-in-StyleGAN2#6]
模型
e4e_ffhq_encode.pt
 stylegan2-ffhq-config-f.pt
在云盘上看不到了，能够再分享以下吗

**Comment by budui** [comment]
stylegan2-ffhq-config-f.pt: https://drive.google.com/file/d/1EM87UquaoQmk17Q8d5kYIAHqu0dkYqdT/view
e4e_ffhq_encode.pt: https://drive.google.com/uc?id=1O8OLrVNOItOJoNGMyQ8G8YRTeTYEfs0P

from https://github.com/omertov/encoder4editing

**Comment by seasm** [comment]
收到，感谢

wrong.wang ***@***.***> 于2023年8月30日周三 22:27写道：
